services:
  - docker

stages:
#  - test
  - name: git_release
    if: branch = master
#  - name: publish
#    if: branch = test_build

jobs:
  include:
#    - stage: test
#      language: python
#      python:
#        - "3.7-dev"
#      before_install:
#        - pip install --upgrade pip
#      install:
#        - pip install codecov
#      script:
#        - make test
#      after_success:
#        - codecov
    - stage: git_release
      before_deploy:
        - git config --local user.name CCardosoDev
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
        - git tag $TRAVIS_TAG
      deploy:
        provider: release
        api_key:
          secure: "GvyL30ka/9zaYnYkas9eiNQ0v/NxLxY8GYqgL/99dCealu8efBNshpoPXfWwxbfkrEA8L2CDZ0hIFBfOSS/ZPns77Soda423MbufcYQpVsKCrc9+c3AjCfeKt8v4in824EBbXzR/cZqfPECcQlSXmldyZ5k31c2RFV36JsyeinSv8Uk861t0K7x99KYiIcDJx0D9MslWML465tlE8In3cpUHhU126juHd7ag55ROYzeaKHRu4JtzzzgfkOWKAZ76MBk1wTwlOboY8b3++xac5bdbwM3wUrfzMEZlejqkWvAFtoS3R0RSZmNRVgt8exitvhZGi3HQVfIYg8lmRyZZMJR47/RRdlM6xVLdyQi0iG5PRb1MzPs3jBYOTN9vmKUzTXggMY+eJhnEdsY0JatEupaj1+8Ek3mW4ejCbYh8Mvz7fUSw075kjW2+zJL+I7N+XbyRBvWJFmA5k8hyV/v2dAeDCvf4Q9HK17wqxmHZX6k89N8yloSkXjXzhHIZDYpyr4PEWYUG9oCA5/RPd7RyVqT2mzHN2XMYDCg+kFMbFeZBZ3PjiZTbB/xwxn8R0v/H0RUpbounqfu3sc7PfkYYaFFeGANI6Dc0tqVYoJWpaW+inWn06+MJUF0lWPsXrL7PvLvz/lS03K6SizTBH7CCHKb4En1it68AvWCVNpJX3e4="
        skip_cleanup: true
        on:
          tags: false
#    - stage: publish
#      language: generic
#      deploy:
#        provider: script
#        script: make docker/publish
#        on:
#          tags: false